app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

//Route::resource('admin/users','AdminUsersController');

Route::get('/admin',function(){
    return view('admin.index');
});



Route::group(['middleware'=>'admin'],function(){

    Route::resource('admin/users','AdminUsersController');
    

});

Route::resource('admin/posts','AdminPostsController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'user_id', 'category_id', 'title','photo_id','body',
    ];
    
    
    public function user()
    {
    
        return $this->belongsTo('App\User');
        
    }
    
    public function photo()
    {
        
        return $this->belongsTo('App\Photo');
        
    }
    public function category()
    {
        
        return $this->belongsTo('App\Category');
        
    }




}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')


@section('content')
    <h1>Create Post</h1>

    {!! Form::open(['method'=>'POST','action'=>'AdminPostsController@store','files'=>true]) !!}

         <div class="form-group">
            {!! Form::label('title','Title:') !!}
            {!! Form::text('title',null,['class'=>'form-control']) !!}
         </div>

        <div class="form-group">
            {!! Form::label('category_id','Category:') !!}
            {!! Form::select('category_id',[''=>'Choose post category']+$category,null,['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('photo_id','Add a Image:') !!}
            {!! Form::file('photo_id',['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('body','Description:') !!}
            {!! Form::textarea('body',null,['class'=>'form-control']) !!}
        </div>


        <div class="form-group">
             {!! Form::submit('Create a post',['class'=>'btn btn-primary']) !!}
        </div>

            {{csrf_field()}}

    {!! Form::close() !!}
    @include('includes.form_error')

@stop

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')


@section('content')
    <h1>Edit Post</h1>
    <div class="col-sm-3">
        <img src="{{$post->photo ?$post->photo->file : 'http://placehold.it/400x400'}}" alt="" class="img-responsive img-rounded">

    </div>
    <div class="col-sm-9">

            {!! Form::model($post,['method'=>'PATCH','action'=>['AdminPostsController@update',$post->id],'files'=>true]) !!}

            <div class="form-group">
                {!! Form::label('title','Title:') !!}
                {!! Form::text('title',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('category_id','Category:') !!}
                {!! Form::select('category_id',[''=>'Choose post category']+$category,null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('photo_id','Add a Image:') !!}
                {!! Form::file('photo_id',['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('body','Description:') !!}
                {!! Form::textarea('body',null,['class'=>'form-control']) !!}
            </div>


            <div class="form-group">
                {!! Form::submit('Update',['class'=>'btn btn-primary']) !!}
            </div>

            {{csrf_field()}}

            {!! Form::close() !!}

                {!! Form::model($post,['method'=>'DELETE','action'=>['AdminPostsController@destroy',$post->id],'files'=>true]) !!}

                <div class="form-group">
                    {!! Form::submit('DELETE ',['class'=>'btn btn-danger ']) !!}
                </div>

            {{csrf_field()}}

            {!! Form::close() !!}
    </div>
    @include('includes.form_error')

@stop

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')


@section('content')
    <h1>All Posts</h1>

    <table class="table">

      <thead>
        <tr>
              <th scope="col">ID</th>
              <th scope="col">PHOTO</th>
              <th scope="col">USER</th>
              <th scope="col">CATEGORY</th>
              <th scope="col">TITLE</th>
              <th scope="col">BODY</th>
              <th scope="col">Created</th>
              <th scope="col">Updated</th>
        </tr>
      </thead>
        @if($posts)
            @foreach($posts as $post)
                  <tbody>
                    <tr>
                        {{--id--}}
                        <td>{{$post->id}}</td>
                        <td><img height="60" src="{{$post->photo ?$post->photo->file : 'http://placehold.it/400x400'}}" alt=""></td>
                        <td>{{ $post->user->name}}</td>
                        <td>{{ $post->category?$post->category->name : 'Uncategoraized'}}</td>
                        <td><a href="{{route('admin.posts.edit',$post->id)}}">{{ $post->title }}</a></td>
                        <td>{{str_limit( $post->body,7) }}</td>
                        <td>{{ $post->created_at->diffForHumans() }}</td>
                        <td>{{ $post->updated_at->diffForHumans() }}</td>
                    </tr>
                  </tbody>
            @endforeach

        @endif
    </table>
    @stop