app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

//Route::resource('admin/users','AdminUsersController');

Route::get('/admin',function(){
    return view('admin.index');
});



Route::group(['middleware'=>'admin'],function(){

    Route::resource('admin/users','AdminUsersController');
    

});

Route::resource('admin/posts','AdminPostsController');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','photo_id','is_active','role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    
    public function role(){
        
        return $this->belongsTo('App\Role');
    }
    
    
    public function photo(){
        
        return $this->belongsTo('App\Photo');
    }
    
    
    public function isAdmin()//this method used in middleware in Admin
    {
        if ( $this->role->name=='Admin' && $this->is_active ==1){
            return true;
        }
        
        return false;
    }
    
    public function post(){
        
        return $this->hasMany('App\Post');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Create User</h1>

    {!! Form::open(['method'=>'POST','action'=>'AdminUsersController@store','files'=>true]) !!}

         <div class="form-group">
            {!! Form::label('name','Name:') !!}
            {!! Form::text('name',null,['class'=>'form-control']) !!}
         </div>

         <div class="form-group">
            {!! Form::label('role_id','Role:') !!}
            {!! Form::select('role_id',[''=>'Choose Option']+$roles,null,['class'=>'form-control']) !!}
         </div>

        <div class="form-group">
            {!! Form::label('email','Email:') !!}
            {!! Form::email('email',null,['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('is_active','Status:') !!}
            {!! Form::select('is_active',array(1=>'Active',0=>'Not Active'),0,['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('photo_id','Image:') !!}
            {!! Form::file('photo_id',null,['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('password','Password:') !!}
            {!! Form::password('password',['class'=>'form-control']) !!}
        </div>




        <div class="form-group">
             {!! Form::submit('Create User',['class'=>'btn btn-primary']) !!}
        </div>

            {{csrf_field()}}

    {!! Form::close() !!}

 @include('includes.form_error')



@stop

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Edit User</h1>

    <div class="col-sm-3">
        <img src="{{$user->photo ?$user->photo->file : 'http://placehold.it/400x400'}}" alt="" class="img-responsive img-rounded">
    
    </div>

    <div class="col-sm-9">
        {!! Form::model($user,['method'=>'PATCH','action'=>['AdminUsersController@update',$user->id],'files'=>true]) !!}

        <div class="form-group">
            {!! Form::label('name','Name:') !!}
            {!! Form::text('name',null,['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('role_id','Role:') !!}
            {!! Form::select('role_id',[''=>'Choose Option']+$roles,null,['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('email','Email:') !!}
            {!! Form::email('email',null,['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('is_active','Status:') !!}
            {!! Form::select('is_active',array(1=>'Active',0=>'Not Active'),null,['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('photo_id','Image:') !!}
            {!! Form::file('photo_id',null,['class'=>'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('password','Password:') !!}
            {!! Form::password('password',['class'=>'form-control']) !!}
        </div>


        <div class="form-group">
            {!! Form::submit(' Save Update',['class'=>'btn btn-success ']) !!}
        </div>
        {!! Form::close() !!}



        {!! Form::model($user,['method'=>'DELETE','action'=>['AdminUsersController@destroy',$user->id],'files'=>true]) !!}

            <div class="form-group">
                 {!! Form::submit('DELETE USER',['class'=>'btn btn-danger ']) !!}
            </div>

                {{csrf_field()}}

        {!! Form::close() !!}

    </div>







    @include('includes.form_error')



@stop

resources/views/admin/user/index.blade.php
@extends('layouts.admin')




@section('content')
    @if(Session::has('deleted_user'))
        <p class="bg-danger">{{Session('deleted_user')}}</p>

        @endif
    <h1>User</h1>
    <table class="table">
      <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Photo</th>
            <th scope="col">Name</th>
            <th scope="col">Role</th>
            <th scope="col">Email</th>
            <th scope="col">Status</th>
            <th scope="col">Created</th>
            <th scope="col">Updated</th>
        </tr>
      </thead>

        @if($users)
            @foreach($users as $user)

              <tbody>
                <tr>
                    <td>{{$user->id}}</td>
                    <td><img height="60" src="{{$user->photo ?$user->photo->file : 'http://placehold.it/400x400'}}" alt=""></td>
                    <td><a href="{{route('admin.users.edit',$user->id)}}">{{$user->name}}</a></td>
                    <td>{{$user->role->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->is_active==1?'Active':'Not active'}}</td>
                    <td>{{$user->created_at->diffForHumans()}}</td>
                    <td>{{$user->updated_at->diffForHumans()}}</td>

                </tr>
              </tbody>
            @endforeach

        @endif
    </table>



@stop